name: 'Create Release Pull Request'
description: 'Creates a pull request on main'
on:
  workflow_call:
    inputs:
      token:
        description: 'GITHUB_TOKEN or a `repo` scoped Personal Access Token (PAT)'
        default: ${{ github.token }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Raise Release PR
        run: |          
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          TITLE="Release ${VERSION%'-SNAPSHOT'}"
          echo "Creating PR ${TITLE}"
          PAYLOAD=$(cat <<EOF
            {
              "title": "${TITLE}",
              "body": "Approve this PR to trigger a release build.",
              "head": "${BRANCH}",
              "base": "main"
            }
          EOF
          )
          curl -L \
            -X POST \
            -H "Authorization: token ${TOKEN}" \
            -H "Content-Type:application/json" \
            https://api.github.com/repos/${REPOSITORY}/pulls \
            -d "$PAYLOAD"
        env:
          BRANCH: ${{ github.ref }}
          REPOSITORY: ${{ github.repository }}
          TOKEN: ${{ inputs.token }}    